# version: "3.8"

services:
  # Frontend Service (React Vite)
  frontend:
    image: izhardev/medium-frontend:latest
    container_name: medium-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:5173
      # - VITE_SOCKET_URL=http://localhost:3001
    depends_on:
      - socket-backend
    restart: unless-stopped
    networks:
      - app-network

  # Socket Backend Service (Express)
  socket-backend:
    image: izhardev/socket-backend:latest
    container_name: socket-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_URL=${DATABASE_URL}
      - CORS_ORIGIN=http://localhost:5173
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: medium-db
    environment:
      - POSTGRES_DB=medium-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
