name = "backend"
compatibility_date = "2024-08-09"

 [vars]
 DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYmNhNjE4ZDktMjVkOS00ZDA2LWFjMzktOWRiZDM3NTUyNDdjIiwidGVuYW50X2lkIjoiYTQxZTNjN2NmYzY5MTIxZGJiOTFhMDFhYTI4YzkzYWI1NTNmNGRmZjgwMWM2NTNiNmQxMmQwOGJkYzliMWY5OSIsImludGVybmFsX3NlY3JldCI6IjcwOWE2NTEyLTJjMmMtNDBhZC05ZGFhLWE2MGYyOTdhZGQwZCJ9.iacn3wCDCiwFl7MWZiqaKJAesY7V_bp6vtajR0a7Tx0"

node_compat = true