name: Deploy to vercel

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install socket-backend dependencies
        working-directory: ./socket-backend
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Build socket backend
        working-directory: ./socket-backend
        run: npm run build
